sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 6
  - 8
  - 10
matrix:
    fast_finish: true
script: "npm run travis"
before_install:
  - npm i -g npm
after_success:
  - npm install -g npx
  - npx -p node@8 npm run semantic-release
