sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 4
  - 6
matrix:
    fast_finish: true
    allow_failures:
env:
  global:
    - BUILD_LEADER_ID=2
    - CXX=g++-4.8
script: "npm run travis"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm install -g npx
  - npx -p node@8 npm run semantic-release
